### ISSUE TITLE
Develop Database

### ISSUE THREAD

**Issue by ernstsh** [ernstsh/CS361#10]
As a software developer, I need a database of materials that can be recycled so that I can query and produce results for my user.
Find initial information set
Create a database table of items
Fill database with initial information set

**Comment by GabeM** [comment]
Database has been built. The structure is as follows:

User: 5 fields. U_Name is the primary key and username, P_Word explains itself, Email does so as well, and Recycled holds the number of times the user has recycled. Is_Admin is a tiny int. It is 0 for all normal users, but can be set to 1 to give an account admin privileges.
Items: 4 fields. I_Name is primary key and item name, Recyclable is a tiny int holding either 0 or 1 to represent whether the item can be recycled, Environmental holds the environmental impact, and Type is a foreign key to the Types table which also says the type of item it is
Types: 3 fields. Type is the primary key and name of the type of item. Description holds the description of recyclables/trash of that type. Disposal is text containing disposal info.
S_Tags: 2 fields, both fields together are the primary key. I_Name is a foreign key referencing an item directly. Tag holds a search tag our algorithm can compare to searches. Due to this structure, we can have multiple tags assigned to the same item for good search functionality.
I_Rec: 2 fields, both primary. U_Name is a foreign key referencing the User table and I_Name is a foreign key referencing the Items table. This table is used to show which items a user has recycled.
Disposal: 2 fields. Primary key is D_Name which holds the name of the disposal company. The second field is URL, which holds the address of their website.
