### ISSUE TITLE
Request new item

### ISSUE THREAD

**Issue by ernstsh** [ernstsh/CS361#3]
Create an admin account for the developers
Create a page which allows a user to write a message and save it to the site
Create page for admin account to view user item requests

**Comment by seanmarty** [comment]
I added addItem.html and itemRequest.php to the code to implement this story.  Super simple, for now it just sends an email to a hard-coded email address (currently my onid email) with the user's input.

Shannon - the addItem page is as barebones as it gets right now.  If you want to add your bootstrap formatting and everything, by all means go ahead.  Otherwise we can just leave it and make a comment on the HW7 write-up.

If I don't hear from you by 8 tonight ill just close this issue.

**Comment by ernstsh** [comment]
I will implement. It should be fine. We won't add the bootstrap. Please add your comments to HW7

**Comment by seanmarty** [comment]
Closing issue just to clean up Github.
